app:
  datasource:
    jdbc-url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    pool-size: 30

spring:
  datasource:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jooq:
    sql-dialect: Postgres